---
- hosts: all
  sudo: true
  tasks:
    - name: install flash repo
      dnf: name=http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
        state=present

    - name: install deps
      dnf: name={{ item }} state=present
      with_items:
        - gcc
        - kernel-headers
        - firefox
        - "@lxde-desktop-environment"
        - flash-plugin

    - name: remove some unwanted packages
      dnf: name={{ item }} state=absent
      with_items:
        - clipit

    - name: update system
      dnf: name=* state=latest

    - name: set gui runlevel
      command: /usr/bin/systemctl set-default graphical.target

    - name: autologin vagrant
      lineinfile: dest=/etc/lxdm/lxdm.conf regexp='^# autologin.*'
        line='autologin=vagrant'
      
    - name: disable screensaver
      lineinfile: dest=/etc/xdg/lxsession/LXDE/autostart regexp='^@xscreensaver.*'
        state=absent
      
    - name: create some directories
      file: path=/home/vagrant/.config/lxsession/LXDE state=directory
        recurse=yes owner=vagrant group=vagrant mode=0700
    - file: path=/home/vagrant/.config/lxpanel/LXDE/panels state=directory
        recurse=yes owner=vagrant group=vagrant mode=0700

    - name: create autostart
      command: /bin/touch /home/vagrant/.config/lxsession/LXDE/autostart

    - name: set file permissions
      file: path=/home/vagrant/.config/lxsession/LXDE/autostart
        state=file owner=vagrant group=vagrant mode=0700

    - name: set firefox to autostart
      command: /usr/bin/echo "@firefox" > /home/vagrant/.config/lxsession/LXDE/autostart

    - name: copy panel config
      copy: dest=/home/vagrant/.config/lxpanel/LXDE/panels/panel
        src=panel owner=vagrant group=vagrant
